cmake_minimum_required(VERSION 4.0)
project(data_structure)

set(CMAKE_CXX_STANDARD 14)

add_executable(func_calculation complexity/func_calculation.cpp)
add_executable(ring_road complexity/ring_road.cpp)
add_executable(conv_travel complexity/conv_travel.cpp)
add_executable(win_lottery complexity/win_lottery.cpp)
